// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Votaciones.Infrastructure.Data;

#nullable disable

namespace Votaciones.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903045347_tableListaCandidato")]
    partial class tableListaCandidato
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Votaciones.Domain.Models.ActaDetalle", b =>
                {
                    b.Property<Guid>("IdActaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CandidatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListaElectoralId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Votos")
                        .HasColumnType("int");

                    b.HasKey("IdActaDetalle");

                    b.HasIndex("ActaId");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("ListaElectoralId");

                    b.ToTable("ActaDetalle");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.ActaEleccion", b =>
                {
                    b.Property<Guid>("IdActa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EleccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MesaElectoralId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoCandidato")
                        .HasColumnType("int");

                    b.Property<int>("TotalVotos")
                        .HasColumnType("int");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioRegistroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VotosBlancos")
                        .HasColumnType("int");

                    b.Property<int>("VotosNulos")
                        .HasColumnType("int");

                    b.HasKey("IdActa");

                    b.HasIndex("EleccionId");

                    b.HasIndex("MesaElectoralId");

                    b.ToTable("ActaEleccion");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.AdmBitacora", b =>
                {
                    b.Property<Guid>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EleccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdRegistro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBitacora");

                    b.HasIndex("EleccionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AdmBitacora", null, t =>
                        {
                            t.HasCheckConstraint("CK_AdmBitacora_ValoresAnteriores_Json", "[ValoresAnteriores] IS NULL OR ISJSON([ValoresAnteriores]) = 1");

                            t.HasCheckConstraint("CK_AdmBitacora_ValoresNuevos_Json", "[ValoresNuevos] IS NULL OR ISJSON([ValoresNuevos]) = 1");
                        });
                });

            modelBuilder.Entity("Votaciones.Domain.Models.AdmRol", b =>
                {
                    b.Property<Guid>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DescripcionRol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermisosRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("AdmRol");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.AdmUsuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuario");

                    b.HasIndex("RolId");

                    b.ToTable("AdmUsuario");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Candidato", b =>
                {
                    b.Property<Guid>("IdCandidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EleccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCandidato")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("TipoCandidato")
                        .HasColumnType("int");

                    b.HasKey("IdCandidato");

                    b.HasIndex("EleccionId");

                    b.ToTable("Candidato");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Canton", b =>
                {
                    b.Property<Guid>("IdCanton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCanton")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProvinciaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdCanton");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Canton");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Eleccion", b =>
                {
                    b.Property<Guid>("IdEleccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEleccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEleccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdEleccion");

                    b.ToTable("Eleccion");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.ListaCandidato", b =>
                {
                    b.Property<Guid>("IdListaCandidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListaElectoralId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ListaPrincipal")
                        .HasColumnType("bit");

                    b.HasKey("IdListaCandidato");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("ListaElectoralId");

                    b.ToTable("ListaCandidato");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.ListaElectoral", b =>
                {
                    b.Property<Guid>("IdListaElectoral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Jurisdiccion")
                        .HasColumnType("int");

                    b.Property<string>("NombreLista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroLista")
                        .HasColumnType("int");

                    b.Property<string>("Siglas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdListaElectoral");

                    b.ToTable("ListaElectoral");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.MesaElectoral", b =>
                {
                    b.Property<Guid>("IdMesaElectoral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoMesa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EleccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoMesa")
                        .HasColumnType("int");

                    b.Property<Guid>("ZonaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdMesaElectoral");

                    b.HasIndex("EleccionId");

                    b.HasIndex("ZonaId");

                    b.ToTable("MesaElectoral");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Parroquia", b =>
                {
                    b.Property<Guid>("IdParroquia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CantonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreParroquia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdParroquia");

                    b.HasIndex("CantonId");

                    b.ToTable("Parroquia");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Provincia", b =>
                {
                    b.Property<Guid>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoProvincia")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("NombreProvincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdProvincia");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Zona", b =>
                {
                    b.Property<Guid>("IdZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreZona")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("ParroquiaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdZona");

                    b.HasIndex("ParroquiaId");

                    b.ToTable("Zona");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.ActaDetalle", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.ActaEleccion", "ActaCab")
                        .WithMany("ActaDetalles")
                        .HasForeignKey("ActaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Votaciones.Domain.Models.Candidato", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId");

                    b.HasOne("Votaciones.Domain.Models.ListaElectoral", "ListaElectoral")
                        .WithMany()
                        .HasForeignKey("ListaElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActaCab");

                    b.Navigation("Candidato");

                    b.Navigation("ListaElectoral");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.ActaEleccion", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Votaciones.Domain.Models.MesaElectoral", "MesaElectoral")
                        .WithMany()
                        .HasForeignKey("MesaElectoralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleccion");

                    b.Navigation("MesaElectoral");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.AdmBitacora", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId");

                    b.HasOne("Votaciones.Domain.Models.AdmUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Eleccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.AdmUsuario", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.AdmRol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Candidato", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Canton", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.ListaCandidato", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.Candidato", "Candidato")
                        .WithMany("ListaCandidatos")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Votaciones.Domain.Models.ListaElectoral", "ListaElectoral")
                        .WithMany()
                        .HasForeignKey("ListaElectoralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("ListaElectoral");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.MesaElectoral", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Votaciones.Domain.Models.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Parroquia", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.Canton", "Canton")
                        .WithMany()
                        .HasForeignKey("CantonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Zona", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.Parroquia", "Parroquia")
                        .WithMany()
                        .HasForeignKey("ParroquiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parroquia");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.ActaEleccion", b =>
                {
                    b.Navigation("ActaDetalles");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Candidato", b =>
                {
                    b.Navigation("ListaCandidatos");
                });
#pragma warning restore 612, 618
        }
    }
}
