// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Votaciones.Infrastructure.Data;

#nullable disable

namespace Votaciones.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Votaciones.Domain.Models.ActaDetalle", b =>
                {
                    b.Property<Guid>("IdActaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Votos")
                        .HasColumnType("int");

                    b.HasKey("IdActaDetalle");

                    b.HasIndex("ActaId");

                    b.HasIndex("CandidatoId");

                    b.ToTable("ActaDetalle");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.ActaEleccion", b =>
                {
                    b.Property<Guid>("IdActa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EleccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MesaElectoralId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalVotos")
                        .HasColumnType("int");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioRegistroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VotosBlancos")
                        .HasColumnType("int");

                    b.Property<int>("VotosNulos")
                        .HasColumnType("int");

                    b.HasKey("IdActa");

                    b.HasIndex("EleccionId");

                    b.HasIndex("MesaElectoralId");

                    b.ToTable("ActaEleccion");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.AdmBitacora", b =>
                {
                    b.Property<Guid>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EleccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdRegistro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBitacora");

                    b.HasIndex("EleccionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AdmBitacora", null, t =>
                        {
                            t.HasCheckConstraint("CK_AdmBitacora_ValoresAnteriores_Json", "[ValoresAnteriores] IS NULL OR ISJSON([ValoresAnteriores]) = 1");

                            t.HasCheckConstraint("CK_AdmBitacora_ValoresNuevos_Json", "[ValoresNuevos] IS NULL OR ISJSON([ValoresNuevos]) = 1");
                        });
                });

            modelBuilder.Entity("Votaciones.Domain.Models.AdmRol", b =>
                {
                    b.Property<Guid>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DescripcionRol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermisosRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("AdmRol");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.AdmUsuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuario");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("AdmUsuario");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Candidato", b =>
                {
                    b.Property<Guid>("IdCandidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EleccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCandidato")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumeroLista")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.HasKey("IdCandidato");

                    b.HasIndex("EleccionId");

                    b.ToTable("Candidato");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Eleccion", b =>
                {
                    b.Property<Guid>("IdEleccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEleccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEleccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdEleccion");

                    b.ToTable("Eleccion");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.MesaElectoral", b =>
                {
                    b.Property<Guid>("IdMesaElectoral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoMesa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EleccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoMesa")
                        .HasColumnType("int");

                    b.HasKey("IdMesaElectoral");

                    b.HasIndex("EleccionId");

                    b.ToTable("MesaElectoral");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.ActaDetalle", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.ActaEleccion", "ActaCab")
                        .WithMany("ActaDetalles")
                        .HasForeignKey("ActaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Votaciones.Domain.Models.Candidato", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActaCab");

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.ActaEleccion", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Votaciones.Domain.Models.MesaElectoral", "MesaElectoral")
                        .WithMany()
                        .HasForeignKey("MesaElectoralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleccion");

                    b.Navigation("MesaElectoral");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.AdmBitacora", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId");

                    b.HasOne("Votaciones.Domain.Models.AdmUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Eleccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.AdmUsuario", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.AdmRol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.Candidato", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.MesaElectoral", b =>
                {
                    b.HasOne("Votaciones.Domain.Models.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("Votaciones.Domain.Models.ActaEleccion", b =>
                {
                    b.Navigation("ActaDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
